- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r2?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r2?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r2?arch=armv7&distro=edge
