- pkg:apk/alpine/prometheus-unbound-exporter-openrc@0.4.6-r5?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-unbound-exporter-openrc@0.4.6-r5?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-unbound-exporter-openrc@0.4.6-r5?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-unbound-exporter-openrc@0.4.6-r5?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-unbound-exporter-openrc@0.4.6-r5?arch=ppc64le&distro=edge
