- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r8?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r7?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter@0.8.0-r7?arch=armhf&distro=latest-stable
