- pkg:apk/alpine/prometheus@3.5.0-r1?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus@3.5.0-r1?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus@3.5.0-r1?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus@3.5.0-r1?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus@2.53.4-r4?arch=aarch64&distro=latest-stable
