- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r3?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r3?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r3?arch=armv7&distro=edge
