- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-wireguard-exporter-openrc@3.6.6-r3?arch=armv7&distro=latest-stable
