- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r2?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.26.0-r10?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.26.0-r10?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.26.0-r10?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.26.0-r10?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.26.0-r10?arch=ppc64le&distro=latest-stable
