- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r28?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=s390x&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=x86&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r27?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=aarch64&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=armhf&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=armv7&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=ppc64le&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=s390x&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=x86&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r17?arch=x86_64&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r19?arch=aarch64&distro=v3.20
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r19?arch=armhf&distro=v3.20
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r19?arch=armv7&distro=v3.20
- pkg:apk/alpine/prometheus-openrc-exporter@0.0.2-r19?arch=ppc64le&distro=v3.20
